discord:
  token: ""
  status: "ONLINE"
  activity:
    type: "PLAYING"
    game: "%player_count% players in server"
    url: ""

needs-verification: true

server-name: "server"

chat-max-length: 150 # 0 = unlimited
chat-max-lines: 0 # 0 = unlimited
chat-max-attachments: 0 # 0 = unlimited

discord-source-name: "Dis"

system-channel: 0

channels:
  global: 0

role-prefix:
  enable: true
  default: "%role_color%"

allow-colors-in-name: true # specifying the role name to limit using colors to only people who have that role.

message-sending-setting:
  join: true
  leave: true
  switch: true
  first-join: true # Requires LuckPerms
