discord:
  token: ""
  status: "ONLINE"
  activity:
    type: "DEFAULT"
    game: "%player_count% players in server"
    url: ""

chat-max-length: 150

discord-souce-name: "Dis"

system-channel: 0

channels:
  global: 0

role-prefix:
  default: "%role_prefix%* "
