name: DiscordChatBridge
main: net.okocraft.discordchatbridge.platform.bukkit.DiscordChatBridgeBukkit
version: ${project.version}
description: ${project.description}
url: ${project.url}
author: Siroshun09
softdepend: [LunaChat]