name: DiscordChatBridge
main: net.okocraft.discordchatbridge.platform.bukkit.DiscordChatBridgeBukkit
version: ${project.version}
api-version: "1.16"
description: ${project.description}
url: ${project.url}
author: Siroshun09
softdepend: [LunaChat, LuckPerms]
commands:
  discordchatbridge:
    aliases: [ "dcb" ]
    description: "Main command containing Link command and Reload command"
