name: Java CI
on: [ push, pull_request ]

jobs:
  build-java-11:
    uses: okocraft/workflows/.github/workflows/maven.yml@v1
    with:
      java-version: '11'
  build-java-16:
    uses: okocraft/workflows/.github/workflows/maven.yml@v1
    with:
      java-version: '16'
  build-java-17:
    uses: okocraft/workflows/.github/workflows/maven.yml@v1
    with:
      java-version: '17'
